### GET
GET http://localhost:8080/coffees

### GET
GET http://localhost:8080/coffees/73e5805e-9854-4026-b0ac-3aeb4177f4ba

### GET
GET http://localhost:8080/coffees/abc

### POST
POST http://localhost:8080/coffees
Content-Type: application/json

{
 "id": "id",
 "name": "coffee"
}

### PUT
PUT http://localhost:8080/coffees/id
Content-Type: application/json

{
  "id": "id2",
  "name": "coffee2"
}

### PUT
PUT http://localhost:8080/coffees/id2
Content-Type: application/json

{
"id": "id2",
"name": "coffee2"
}

### DELETE
DELETE http://localhost:8080/coffees/id

### GET greeting
GET http://localhost:8080/greeting

###
GET http://localhost:8080/greeting/coffee

### GET droid
GET http://localhost:8080/droid

### GET actuator
GET http://localhost:8080/actuator

### GET actuator/health
GET http://localhost:8080/actuator/health

### GET actuator/env
GET http://localhost:8080/actuator/env